# Generated by Django 5.2.1 on 2025-09-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='calculos/')),
                ('tipo_archivo', models.CharField(choices=[('INV', 'Inventario'), ('VEN', 'Ventas'), ('PRO', 'Producción')], max_length=3)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('saldo_inventario', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cantidad_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_produccion', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['producto', '-fecha_calculo'],
            },
        ),
    ]
