# Generated by Django 5.2.1 on 2025-09-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadocalculo',
            name='cantidad_pendiente',
        ),
        migrations.RemoveField(
            model_name='resultadocalculo',
            name='saldo_inventario',
        ),
        migrations.RemoveField(
            model_name='resultadocalculo',
            name='saldo_produccion',
        ),
        migrations.AddField(
            model_name='resultadocalculo',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ventas - Total Disponible', max_digits=15),
        ),
        migrations.AddField(
            model_name='resultadocalculo',
            name='inventario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo actual en inventario', max_digits=15),
        ),
        migrations.AddField(
            model_name='resultadocalculo',
            name='produccion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo por entregar de producción', max_digits=15),
        ),
        migrations.AddField(
            model_name='resultadocalculo',
            name='total_disponible',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma de inventario y producción', max_digits=15),
        ),
        migrations.AddField(
            model_name='resultadocalculo',
            name='ventas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad pendiente de ventas', max_digits=15),
        ),
    ]
