# Generated by Django 5.2.1 on 2025-09-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_calculator', '0002_remove_resultadocalculo_cantidad_pendiente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultadocalculo',
            options={'ordering': ['codigo', 'referencia', '-fecha_calculo']},
        ),
        migrations.RemoveField(
            model_name='resultadocalculo',
            name='producto',
        ),
        migrations.AddField(
            model_name='resultadocalculo',
            name='codigo',
            field=models.CharField(default='', help_text='Código del producto sin los últimos 3 dígitos', max_length=97),
        ),
        migrations.AddField(
            model_name='resultadocalculo',
            name='referencia',
            field=models.CharField(default='', help_text='Últimos 3 dígitos del producto', max_length=3),
        ),
    ]
