# Generated by Django 5.2.1 on 2025-09-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_calculator', '0003_alter_resultadocalculo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultadocalculo',
            options={'ordering': ['referencia', 'talla', '-fecha_calculo']},
        ),
        migrations.RemoveField(
            model_name='resultadocalculo',
            name='codigo',
        ),
        migrations.AddField(
            model_name='resultadocalculo',
            name='talla',
            field=models.CharField(default='', help_text='Talla del producto', max_length=3),
        ),
        migrations.AlterField(
            model_name='resultadocalculo',
            name='referencia',
            field=models.CharField(default='', help_text='Referencia del producto sin la talla', max_length=97),
        ),
    ]
