# Generated by Django 5.2.4 on 2025-07-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='excels/')),
                ('consecutivo', models.IntegerField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
