# Generated by Django 5.2.4 on 2025-08-05 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_processor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(blank=True, max_length=100, null=True)),
                ('produccion', models.CharField(blank=True, max_length=100, null=True)),
                ('cant_orig', models.FloatField(blank=True, null=True)),
                ('saldo_entregar', models.FloatField(blank=True, null=True)),
                ('cant_produc', models.FloatField(blank=True, null=True)),
                ('iny', models.CharField(blank=True, max_length=20, null=True)),
                ('otros', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='excel_processor.excelprocess')),
            ],
        ),
    ]
