# Generated by Django 5.2.1 on 2025-09-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_processor', '0002_registroexcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFProcessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=500)),
                ('output_path', models.CharField(blank=True, max_length=500, null=True)),
                ('process_date', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_batch', models.BooleanField(default=False)),
            ],
        ),
    ]
