# Generated by Django 5.2.1 on 2025-09-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_processor', '0003_pdfprocesshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfprocesshistory',
            name='pages',
            field=models.IntegerField(default=0),
        ),
    ]
