# Generated by Django 5.2.1 on 2025-09-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_processor', '0004_pdfprocesshistory_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroexcel',
            options={'ordering': ['-fecha_registro']},
        ),
        migrations.AddField(
            model_name='registroexcel',
            name='origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
