# Generated by Django 5.2.1 on 2025-09-12 14:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='production_sheets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])])),
                ('origin', models.CharField(choices=[('BANDA_1_2', 'Banda 1 y 2'), ('BANDA_4', 'Banda 4')], max_length=10)),
                ('manifest_number', models.CharField(max_length=100)),
                ('packing_date', models.DateField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=3)),
                ('quantity', models.IntegerField(default=0)),
                ('production_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_sheets.productionsheet')),
            ],
            options={
                'unique_together': {('production_sheet', 'op', 'ref', 'size')},
            },
        ),
    ]
