# Generated by Django 5.2.1 on 2025-09-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_sheets', '0002_clean_duplicates_and_add_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productionsheet',
            name='unique_manifest_number',
        ),
    ]
